### ISSUE TITLE
Route not found when containing URL encoded characters

### ISSUE THREAD

**Issue by vvasiloi** [stefandoorn/SyliusSeoUrlPlugin#12]
Problem:
Both `RequestContext::checkProductSlug` and `RequestContext::checkTaxonSlug` receive the slug from `Symfony\Component\HttpFoundation\Request::getPathInfo`, which returns the raw path, not URL decoded, so when it contains Unicode characters or any URL encoded characters, the route matching will fail.

Steps to reproduce:
1. Create a product or taxon with slug containing Unicode characters, like Germanic umlauts (ä, ö, ü) or French accents.
2. Go to the respective product show or index page.

Possible solution:
Apply `urldecode` on the slug in [RequestContext::prepareSlug](https://github.com/stefandoorn/SyliusSeoUrlPlugin/blob/fccb2ef7e503a26cea1edfa967e7b3cb3392ee3a/src/Routing/RequestContext.php#L51)

**Comment by stefandoorn** [comment]
Nice, would you be able to provide a PR and if possible including some tests?

**Comment by vvasiloi** [comment]
@stefandoorn ok, I will try to do it in weekend.
