### ISSUE TITLE
Add suport Symfony 5 & Sylius 1.9

### ISSUE THREAD

**Issue by Loocos** [stefandoorn/SyliusSeoUrlPlugin#16]
HI,

new TreeBuilder() in DependencyInjection/Configuration.php need a name parameter to be working (the same as the root func parameter)
And you've to remove the root line function

Thanks

**Comment by kevinbalicot** [comment]
Hi !

Please can you fix this issue ?

Maybe you can change `DependencyInjection/Configuration.php` like your other plugin https://github.com/stefandoorn/sitemap-plugin/blob/master/src/DependencyInjection/Configuration.php#L15.

Thanks you !

**Comment by stefandoorn** [comment]
Ah sorry, I didn't see the messages. Is someone able to submit a PR? That would be a great help :)

**Comment by stefandoorn** [comment]
I think it should be working now :-)
